export const northernRegion = [
  "Hà Giang",
  "Cao Bằng",
  "Bắc Kạn",
  "Lạng Sơn",
  "Tuyên Quang",
  "Thái Nguyên",
  "Phú Thọ",
  "Bắc Giang",
  "Quảng Ninh",
  "Lào Cai",
  "Lai Châu",
  "Yên Bái",
  "Điện Biên",
  "Sơn La",
  "Hòa Bình",
  "Bắc Ninh",
  "Hà Nam",
  "Hà Nội",
  "Hải Dương",
  "Hải Phòng",
  "Hưng Yên",
  "Nam Định",
  "Ninh Bình",
  "Thái Bình",
  "Vĩnh Phúc",
];

export const centralRegion = [
  "Thanh Hoá",
  "Nghệ An",
  "Hà Tĩnh",
  "Quảng Bình",
  "Quảng Trị",
  "Thừa Thiên-Huế",
  "Kon Tum",
  "Gia Lai",
  "Đắc Lắc",
  "Đắc Nông",
  "Lâm Đồng",
  "Đà Nẵng",
  "Quảng Nam",
  "Quảng Ngãi",
  "Bình Định",
  "Phú Yên",
  "Khánh Hoà",
  "Ninh Thuận",
  "Bình Thuận",
];

export const southernRegion = [
  "Bình Dương",
  "Bình Phước",
  "Tây Ninh",
  "Bà Rịa - Vũng Tàu",
  "Đồng Nai",
  "Long An",
  "Bến Tre",
  "Kiên Giang",
  "Vĩnh Long",
  "Trà Vinh",
  "Đồng Tháp",
  "Hậu Giang",
  "TP. Hồ Chí Minh",
  "Cần Thơ",
  "Tiền Giang",
  "An Giang",
  "Sóc Trăng",
  "Bạc Liêu",
  "Cà Mau",
];

export const provinceVN = [
  ...northernRegion,
  ...centralRegion,
  ...southernRegion,
];
